title: Creve Coeur Sailing Association
description: Come Sail With Us!
theme: minimal-mistakes-jekyll
include: ["_pages", "_posts"]
encoding: "utf-8"
url: "https://www.sailccsa.com"
plugins:
  - jekyll-sitemap
analytics:
  provider: "google-gtag"
  google:
    tracking_id: 'G-1VPFV206DC'
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  # _about-us
  - scope:
      path: ""
      type: about-us
    values:
      layout: single
  # _events
  - scope:
      path: ""
      type: events
    values:
      layout: single
  # _learning
  - scope:
      path: ""
      type: learning
    values:
      layout: single
  # _links-for-sailors
  - scope:
      path: ""
      type: links-for-sailors
    values:
      layout: single
  # _news
  - scope:
      path: ""
      type: news
    values:
      layout: single
  # _sailing
  - scope:
      path: ""
      type: sailing
    values:
      layout: single
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
collections:
  about-us:
    output: true
    permalink: /:collection/:path
  events:
    output: true
    permalink: /:collection/:path
  learning:
    output: true
    permalink: /:collection/:path
  links-for-sailors:
    output: true
    permalink: /:collection/:path
  news:
    output: true
    permalink: /:collection/:path
  sailing:
    output: true
    permalink: /:collection/:path
