name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build and deploy
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.TOKEN }}
